name: nbudget
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  adaptive_theme: ^1.1.0
  animations: ^2.0.0
  calendarro: ^1.2.0
  cloud_firestore: ^1.0.1
  connectivity: ^3.0.3
  cupertino_icons: ^1.0.0 
  date_util: ^0.1.4
  firebase_auth: ^1.0.1
  flutter_keyboard_visibility: ^5.0.2
  flutter_rounded_date_picker: ^2.0.0
  flutter_slidable: ^0.6.0
  fluttertoast: ^7.1.8
  get_storage: ^2.0.2
  hexcolor: ^1.0.6
  intl: ^0.17.0
  introduction_screen: ^2.1.0
  provider: ^4.3.3 
  rxdart: ^0.25.0
  url_launcher: ^6.0.6

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
  r_resources: ^0.0.6    
  build_runner: ^2.0.3
  flutter_native_splash: ^1.1.8+4

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  android: true
  ios: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logoApp.png"
mage_dark: assets/images/logo.png

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/strings/

flutter_intl:
  enabled: true
