name: nbudget
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0
  hexcolor: ^1.0.6
  intl: ^0.16.1
  date_util: ^0.1.4
  firebase_auth: ^0.20.1
  cloud_firestore: ^0.16.0+1
  provider: ^4.3.3
  fluttertoast: ^7.1.8
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  
  uses-material-design: true