/// THIS FILE IS GENERATED BY r_resources. DO NOT MODIFY MANUALLY.

// ignore_for_file: avoid_classes_with_only_static_members,always_specify_types,lines_longer_than_80_chars,non_constant_identifier_names,prefer_double_quotes,unnecessary_raw_strings,use_raw_strings

import 'package:flutter/material.dart';

class R {
  static const images = _ImageResources();
  static const svg = _SvgResources();
  static const fonts = _FontResources();
  static _Strings stringsOf(BuildContext context) => _Strings.of(context);
}

class _ImageResources {
  const _ImageResources();

  /// ![](C:\flutterProject\N.Budget-Android\assets/images/logo.png)
  final logo = r'assets/images/logo.png';

  /// ![](C:\flutterProject\N.Budget-Android\assets/images/logoApp.png)
  final logo_app = r'assets/images/logoApp.png';

  /// ![](C:\flutterProject\N.Budget-Android\assets/images/logoWhite.png)
  final logo_white = r'assets/images/logoWhite.png';
}

class _SvgResources {
  const _SvgResources();
}

class _FontResources {
  const _FontResources();
}

class _Strings {
  const _Strings(this.locale);

  static const _fallbackLocale = Locale('en');
  final Locale locale;

  static _Strings of(BuildContext context) {
    return Localizations.of<_Strings>(context, _Strings);
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'signInButtonAuth': 'Sign in',
      'signUpButtonAuth': 'Sign up',
      'loginHintAuth': 'Login',
      'passwordHintAuth': 'Password',
      'labelsignInAuth': 'Sign in',
      'labelsignUpAuth': 'Sign up',
      'labelBottomSignUpAuth': 'Not registered? Sign up!',
      'labelBottomSignInAuth': 'Already registered? Log in!',
      'emptyTextFieldAuth': 'Login or password fields cannot be empty',
      'emptyUserAuth': 'Wrong email or password entered',
      'incorrectEmailAuth': 'Incorrect email input',
      'incorrectPasswordAuth':
          'Incorrect password entry. The string must contain at least one number, one special character, a Latin letter in upper and lower case, the string consists of at least 6 characters',
      'successfulSignUpAuth': 'You have successfully registered',
      'nameApp': 'N.Budget',
      'balanceMonthFirstBlock': 'Until the end of the month',
      'incomeI': 'Income',
      'mandatoryExpenses': 'Mandatory expenses',
      'freeMoney': 'Free money',
      'dailyBudget': 'Today you can spend',
      'incomeLabel': 'Add income',
      'costsLabel': 'Add costs',
      'saveData': 'Save',
      'symbolMoney': '\$',
      'title': 'Title...',
      'comment': 'Comment...',
      'datePickerActionButton': 'Today',
      'zeroMoney': '0.0',
      'historyContainer': 'History',
      'conntectionState': 'No internet connection',
      'forgotPassword': 'Forgot password',
      'messageSentToEmail':
          'An email to reset your password was sent to your email address',
      'welcome': 'Welcome',
      'getStarted': 'Get started',
      'welcomeText':
          'Thank you for downloading our app. N. Budget is an app to keep a budget. With it, you can easily keep track of your spending and you will know how much is left until the end of the month',
      'welcomeTextFoundError':
          'If you find a bug or have a suggestion on how to improve the app, please write to our email nbudget.help@gmail.com.',
      'deleteHistory': 'Delete',
      'showOnlyCosts': 'Costs',
      'showOnlyIncome': 'Income',
      'showAllHistory': 'All history',
      'selectedFilter': 'Selected: ',
    },
    'ru': {
      'signInButtonAuth': 'Войти',
      'signUpButtonAuth': 'Зарегистрироваться',
      'loginHintAuth': 'Логин',
      'passwordHintAuth': 'Пароль',
      'labelsignInAuth': 'Авторизация',
      'labelsignUpAuth': 'Регистрация',
      'labelBottomSignUpAuth': 'Не зарегистрирован? Зарегистрируйся!',
      'labelBottomSignInAuth': 'Уже зарегистрирован? Авторизируйся!',
      'emptyTextFieldAuth': 'Поля логина или пароля не могут быть пустыми',
      'emptyUserAuth': 'Неправильно введён логин или пароль',
      'incorrectEmailAuth': 'Некорректный ввод email',
      'incorrectPasswordAuth':
          'Некорректный ввод пароля. Строка должна содержать хотя бы одно число, один спецсимвол, латинскую букву в верхнем и нижнем регистре, строка состоит не менее, чем из 6 символов',
      'successfulSignUpAuth': 'Вы успешно зарегистрированы',
      'balanceMonthFirstBlock': 'До конца месяца осталось',
      'incomeI': 'Доход',
      'mandatoryExpenses': 'Обязательные траты',
      'freeMoney': 'Свободных денег',
      'dailyBudget': 'Сегодня можно потратить',
      'incomeLabel': 'Добавить доход',
      'costsLabel': 'Добавить расходы',
      'saveData': 'Сохранить',
      'symbolMoney': '₽',
      'title': 'Название...',
      'comment': 'Комментарий...',
      'datePickerActionButton': 'Сегодня',
      'zeroMoney': '0.0',
      'historyContainer': 'История',
      'conntectionState': 'Нет подключения к интернету',
      'forgotPassword': 'Забыл пароль',
      'messageSentToEmail': 'Письмо для сброса пароля было отправлено на почту',
      'welcome': 'Добро пожаловать',
      'getStarted': 'Начать',
      'welcomeText':
          'Спасибо, что скачали наше приложение. N.Budget - это приложение, чтобы вести бюджет. Вместе с ним ты можешь запросто следить за своими тратами и будешь знать сколько осталось до конца месяца.',
      'welcomeTextFoundError':
          'Если вы обнаружили какую-то ошибку или у вас есть предложение как улучшить приложение, то пишите на нашу почту nbudget.help@gmail.com.',
      'deleteHistory': 'Удалить',
      'showOnlyCosts': 'Траты',
      'showOnlyIncome': 'Доход',
      'showAllHistory': 'Вся история',
      'selectedFilter': 'Выбран: ',
    },
  };

  String _getString(String code) {
    return _localizedValues[locale.toString()][code] ??
        _localizedValues[_fallbackLocale.toString()][code] ??
        code;
  }

  /// 'Sign in'
  String get signInButtonAuth => _getString('signInButtonAuth');

  /// 'Sign up'
  String get signUpButtonAuth => _getString('signUpButtonAuth');

  /// 'Login'
  String get loginHintAuth => _getString('loginHintAuth');

  /// 'Password'
  String get passwordHintAuth => _getString('passwordHintAuth');

  /// 'Sign in'
  String get labelsignInAuth => _getString('labelsignInAuth');

  /// 'Sign up'
  String get labelsignUpAuth => _getString('labelsignUpAuth');

  /// 'Not registered? Sign up!'
  String get labelBottomSignUpAuth => _getString('labelBottomSignUpAuth');

  /// 'Already registered? Log in!'
  String get labelBottomSignInAuth => _getString('labelBottomSignInAuth');

  /// 'Login or password fields cannot be empty'
  String get emptyTextFieldAuth => _getString('emptyTextFieldAuth');

  /// 'Wrong email or password entered'
  String get emptyUserAuth => _getString('emptyUserAuth');

  /// 'Incorrect email input'
  String get incorrectEmailAuth => _getString('incorrectEmailAuth');

  /// 'Incorrect password entry. The string must contain at least one number, one special character, a Latin letter in upper and lower case, the string consists of at least 6 characters'
  String get incorrectPasswordAuth => _getString('incorrectPasswordAuth');

  /// 'You have successfully registered'
  String get successfulSignUpAuth => _getString('successfulSignUpAuth');

  /// 'N.Budget'
  String get nameApp => _getString('nameApp');

  /// 'Until the end of the month'
  String get balanceMonthFirstBlock => _getString('balanceMonthFirstBlock');

  /// 'Income'
  String get incomeI => _getString('incomeI');

  /// 'Mandatory expenses'
  String get mandatoryExpenses => _getString('mandatoryExpenses');

  /// 'Free money'
  String get freeMoney => _getString('freeMoney');

  /// 'Today you can spend'
  String get dailyBudget => _getString('dailyBudget');

  /// 'Add income'
  String get incomeLabel => _getString('incomeLabel');

  /// 'Add costs'
  String get costsLabel => _getString('costsLabel');

  /// 'Save'
  String get saveData => _getString('saveData');

  /// '\$'
  String get symbolMoney => _getString('symbolMoney');

  /// 'Title...'
  String get title => _getString('title');

  /// 'Comment...'
  String get comment => _getString('comment');

  /// 'Today'
  String get datePickerActionButton => _getString('datePickerActionButton');

  /// '0.0'
  String get zeroMoney => _getString('zeroMoney');

  /// 'History'
  String get historyContainer => _getString('historyContainer');

  /// 'No internet connection'
  String get conntectionState => _getString('conntectionState');

  /// 'Forgot password'
  String get forgotPassword => _getString('forgotPassword');

  /// 'An email to reset your password was sent to your email address'
  String get messageSentToEmail => _getString('messageSentToEmail');

  /// 'Welcome'
  String get welcome => _getString('welcome');

  /// 'Get started'
  String get getStarted => _getString('getStarted');

  /// 'Thank you for downloading our app. N. Budget is an app to keep a budget. With it, you can easily keep track of your spending and you will know how much is left until the end of the month'
  String get welcomeText => _getString('welcomeText');

  /// 'If you find a bug or have a suggestion on how to improve the app, please write to our email example@gmail.com.'
  String get welcomeTextFoundError => _getString('welcomeTextFoundError');

  /// 'Delete'
  String get deleteHistory => _getString('deleteHistory');

  /// 'Costs'
  String get showOnlyCosts => _getString('showOnlyCosts');

  /// 'Income'
  String get showOnlyIncome => _getString('showOnlyIncome');

  /// 'All history'
  String get showAllHistory => _getString('showAllHistory');

  /// 'Selected: '
  String get selectedFilter => _getString('selectedFilter');
}

class RStringsDelegate extends LocalizationsDelegate<_Strings> {
  const RStringsDelegate();

  static const supportedLocales = [
    Locale('en'),
    Locale('ru'),
  ];

  static const fallbackLocale = Locale('en');

  @override
  bool isSupported(Locale locale) => supportedLocales.contains(locale);

  @override
  Future<_Strings> load(Locale locale) async {
    return _Strings(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<_Strings> old) => false;
}
